/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("org.javamodularity.moduleplugin:org.javamodularity.moduleplugin.gradle.plugin:2.0.0")
    implementation("org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:0.1.0")
    implementation("io.micronaut.minimal.library:io.micronaut.minimal.library.gradle.plugin:4.6.1")
    implementation("org.beryx.jlink:org.beryx.jlink.gradle.plugin:3.2.0")
}
